/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.9.0"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    application
}

application { mainClass.set("example.AppKt") }

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test")

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Ktor
    implementation("io.ktor:ktor-server-core:2.3.3")
    implementation("io.ktor:ktor-server-cio:2.3.3")
    implementation("io.ktor:ktor-server-status-pages:2.3.3")
    implementation("io.ktor:ktor-server-default-headers:2.3.3")
    testImplementation("io.ktor:ktor-server-test-host:2.3.3")

    // JSON serialiaiser
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0-RC")

    // Lib src
    implementation(project(":lib"))
}

testing {
    suites {
        // Configure the built-in test suite
        val test by
                getting(JvmTestSuite::class) {
                    // Use Kotlin Test test framework
                    useKotlinTest()
                }
    }
}
