/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package abgier.di.poc

import kotlin.test.Test
import kotlin.test.assertTrue

class DependencyInjectionContainerTest {
    @Test fun containerInjectsAndProvides() {
        val container = DependencyInjectionContainer()

        container
            .addSingleton<IServiceA>(ServiceA())
            .addSingleton<IRequiresA, RequiresA>()

        assertTrue(container.provide<IServiceA>().exists())
        assertTrue(container.provide<IRequiresA>().containsA())

    }
}


interface IServiceA {
    fun exists(): Boolean
}

class ServiceA : IServiceA {
    override fun exists(): Boolean {
        return true
    }
}

interface IRequiresA {
    fun containsA(): Boolean
}

class RequiresA : IRequiresA {
    val a: IServiceA

    constructor(arg: IServiceA) {
        this.a = arg
    }

    override fun containsA(): Boolean
    {
        return this.a != null
    }
}