/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package abgier.di.poc

import kotlin.test.Test
import kotlin.test.assertTrue

class DependencyInjectionContainerTest {
    
    @Test fun canInjectAndProvide() {
        val container = DependencyInjectionContainer()
        
        container
            .injectFactory<ILogger>({parent -> Logger(parent) as ILogger})
            .inject<IService, Service>()

        assertTrue(container.provide<IService>().someMethod())
    }

    @Test fun singletonFactoriesUsesCorrectClass() {
        val container = DependencyInjectionContainer()
        
        container
            .injectFactory<ILogger>({parent -> Logger(parent)})

        val dummyLogger = container.provideFactory<ILogger, Dummy>()
        assertTrue(dummyLogger != null)

        dummyLogger.info("Hello World")
    }

    @Test fun factoryClassesAreCached() {
        val container = DependencyInjectionContainer()
        
        container
            .injectFactory<ILogger>({parent -> Logger(parent)})

        val dummyLoggerFirst = container.provideFactory<ILogger, Dummy>()
        val dummyLoggerSecond = container.provideFactory<ILogger, Dummy>()
        assertTrue(dummyLoggerFirst == dummyLoggerSecond)
    }
}

class Dummy {

}

interface ILogger {
    fun info(message: String)
}


class Logger : ILogger {
    private val parentClass: java.lang.Class<Any>

    constructor(parentClass: java.lang.Class<Any>) {
        this.parentClass = parentClass
    }

    override fun info(message: String) {
        println("${this.parentClass.getName()}::${message}")
    }
}

interface IService {
    fun someMethod(): Boolean
}

class Service : IService {
    val logger: ILogger

    constructor(logger: ILogger) {
        this.logger = logger
    }

    override fun someMethod(): Boolean
    {
        this.logger.info("Hello World")
        return true
    }
}