/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package abgier.di.poc

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val lib = Library()
        lib.inject(A::class.java, A::class.java)
        lib.inject<AnyRequiresA>(AnyRequiresA::class.java, RequiresA::class.java)
    }
}


class A {
    fun exists() {
        println("A exists")

        // return true
    }
}

interface IRequiresA {
    fun containsA()
}

class AnyRequiresA : IRequiresA {
    val impl: IRequiresA

    constructor(impl: IRequiresA) {
        this.impl = impl
    }

    override fun containsA()
    {
        return this.impl.containsA();
    }
}

class RequiresA : AnyRequiresA {
    val a: A

    constructor(arg: A) {
        println("Constructing Requires A")
        this.a = arg
    }

    override fun containsA()
    {
        return this.a.exists();
    }
}