/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package abgier.di.poc

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val lib = Library()
        lib.inject<IA, A>()
        lib.inject<IRequiresA, RequiresA>()
        // assertTrue(lib.provide<IRequiresA>() !== null)
    }
}


interface IA {
    fun exists()
}

class A : IA {
    override fun exists() {
        println("I exist")
    }
}

interface IRequiresA {
    fun containsA()
}

class RequiresA : IRequiresA {
    val a: IA

    constructor(arg: IA) {
        this.a = arg
    }

    override fun containsA()
    {
        if (this.a != null) {
            println("Contians A")
        }
    }
}