/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.di.poc

import kotlin.test.Test
import kotlin.test.assertTrue
import kotlin.test.assertFailsWith

class DependencyInjectionContainerTest {
    
    @Test fun canInjectAndProvide() {
        val container = DependencyInjectionContainer()
        
        container
            .injectTransient<ILogger, Logger>()
            .injectScoped<IService, Service>()

        val scope = container.createScope()
        val service = scope.provide<IService>()

        assertTrue(service.someMethod() == "Service")
        service.logger.configure(service)

        // TODO: assertion and stdout
        service.logger.info("Test")
    }

    @Test fun canInjectAndReplace() {
        val container = DependencyInjectionContainer()
        
        container
            .injectTransient<ILogger, Logger>()
            .injectScoped<IService, Service>()
            .injectScoped<IService, SomeService>()

        val scope = container.createScope()
        val service = scope.provide<IService>()

        assertTrue(service.someMethod() == "SomeService")
    }

    @Test fun throwsWhenProvidingRemoved() {
        val container = DependencyInjectionContainer()
        
        container
            .injectTransient<ILogger, Logger>()
            .injectScoped<IService, Service>()

        container.remove<IService>()

        val scope = container.createScope()
        assertFailsWith<Exception>(
            message = "Instance for interface com.di.poc.IService could not be fetched",
            block = {
                scope.provide<IService>()
            }
        )
    }

    @Test fun singletonDependencyEquality() {
        val container = DependencyInjectionContainer()
        
        container
            .injectSingleton<Dummy, Dummy>()

        val scope = container.createScope()
        val serviceA = scope.provide<Dummy>()
        val serviceB = scope.provide<Dummy>()
        assertTrue(serviceA == serviceB)
    }

    @Test fun transientDependencyInequality() {
        val container = DependencyInjectionContainer()
        
        container
            .injectTransient<ILogger, Logger>()

        val scope = container.createScope()
        val loggerA = scope.provide<ILogger>()
        val loggerB = scope.provide<ILogger>()
        assertTrue(loggerA != loggerB)
    }

    @Test fun scopedCacheEquality() {
        val container = DependencyInjectionContainer()
        
        container
            .injectTransient<ILogger, Logger>()
            .injectScoped<IService, Service>()

        val scope = container.createScope()
        val serviceA = scope.provide<IService>()
        val serviceB = scope.provide<IService>()
        assertTrue(serviceA == serviceB)
    }

    @Test fun transientScopedInequality() {
        val container = DependencyInjectionContainer()
        
        container
            .injectTransient<ILogger, Logger>()
            .injectTransient<IService, Service>()

        val scope = container.createScope()
        val serviceA = scope.provide<IService>()
        val serviceB = scope.provide<IService>()
        assertTrue(serviceA != serviceB)
    }
}

class Dummy {

}

interface ILogger {
    fun <T : Any>configure(forInstance: T)
    fun info(message: String)
}


class Logger : ILogger {
    private var prefix = ""

    override fun <T : Any>configure(forInstance: T) {
        this.prefix = forInstance::class.java.getName()
    }

    override fun info(message: String) {
        println("${this.prefix}::${message}")
    }
}

interface IService {
    val logger: ILogger

    fun someMethod(): String
}

class Service : IService {
    override val logger: ILogger

    constructor(logger: ILogger) {
        this.logger = logger
    }

    override fun someMethod(): String
    {
        return "Service"
    }
}

class SomeService : IService {
    override val logger: ILogger

    constructor(logger: ILogger) {
        this.logger = logger
    }

    override fun someMethod(): String
    {
        return "SomeService"
    }
}