/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package abgier.di.poc

class Library {
    private val services = mutableMapOf<java.lang.Class<Any>, java.lang.Object>()

    // T should extend type or == type
    fun <T>inject(service: java.lang.Class<T>, type: java.lang.Class<T>) {
        val primaryConstructor = service.getConstructors()[0]

        val params = mutableListOf<Any>()
        for (param in primaryConstructor.getParameters()) {
            val matchingService = this.services.get(param.type)
            if (matchingService != null) {
                params.add(matchingService)
            }
        }

        println("$service being injected with args $params")

        val instance = primaryConstructor.newInstance(*params.toTypedArray())
        this.services.put(type as java.lang.Class<Any>, instance as java.lang.Object)
    }
}

