/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package example

import container.DependencyInjectionContainer
import example.mocks.MockRandomProvider
import example.services.IRandomStringsService
import example.utils.IRandomProvider
import example.utils.createClient
import kotlin.test.Test
import kotlin.test.assertEquals

class RandomStringsServiceTest {

  @Test
  fun CanGetRandomStrings() {
    // Arrange
    val container =
        DependencyInjectionContainer()
            .injectServices()
            .injectHttpContextAccessor()
            .injectSingleton<IRandomProvider>(MockRandomProvider("<random>"))

    // Act
    val client = container.createClient<IRandomStringsService>()
    val res = client.GetRandomStrings()

    // Assert
    assertEquals(listOf("<random>", "<random>", "<random>"), res)
  }
}
